Feature/store corporate actions
alpacahq/marketstore pull request #384
Opened 2020-11-03 16:16 UTC by kulcsarb

Requesting early review

2020-11-09 16:29 UTC, tibkiss commented on contrib/ice/reorg/import.go
> +			if !reimport {
else is not required

2020-11-09 16:29 UTC, tibkiss commented on contrib/ice/sirs/collect.go
> +Loads the listed security files and returns a map of cusipid -> symbol pairs.
Using go's conventions docstrings should start with the function name:
`BuildSecurityMasterMap loads the listed security files ....`

2020-11-09 16:29 UTC, tibkiss commented on contrib/ice/sirs/parser.go
> +	copied from Ledgie
this comment should be removed

2020-11-09 16:29 UTC, tibkiss commented on uda/adjust/caloader.go
> +		return nil
would it make sense to return `err` here?

2020-11-12 15:36 UTC, kalmant commented on Makefile
> +	${MAKE} debug -C contrib/ice
The rest of the plugins are in alphabetical order

2020-11-12 15:37 UTC, kalmant commented on Makefile
> +	${MAKE} -C contrib/ice
Same comment as above

2020-11-12 15:40 UTC, kalmant commented on contrib/ice/Makefile
> +debug:
debug is empty

2020-11-13 13:33 UTC, kalmant requested changes

2020-11-13 13:33 UTC, kalmant commented on contrib/ice/sirs/parser.go
> +func parseDate(value string) (*date.Date, error) {
I can't tell, so I'll ask: is the `nil` value for `*date.Date` handled properly where this is called? It may be, I can't tell.

2020-11-13 13:33 UTC, kalmant commented on contrib/polygon/api/api.go
> +	unadjusted bool) (*HistoricAggregates, error) {
Heads up: this may end up conflicting with #391

2020-11-13 13:33 UTC, kalmant commented on frontend/query.go
> +		aggfunc.SetTimeBucketKey(tbk)
Can you please explain this change?

2020-11-13 13:33 UTC, kalmant commented on uda/datatypes.go
> +		SetTimeBucketKey() set the TimeBucketKey for the aggregator function
[minor] set**s**

2020-11-13 13:33 UTC, kalmant commented on uda/gap/gap.go
> +	SetTimeBucketKey()
Empty

2020-11-13 13:33 UTC, kalmant commented on uda/min/min.go
> +	SetTimeBucketKey()
Empty

2020-11-13 13:33 UTC, kalmant commented on uda/adjust/caloader.go
> +func (act *Actions) FromColumnSeries(cs *io.ColumnSeries) {
exported

2020-11-13 13:33 UTC, kalmant commented on uda/adjust/caloader.go
> +func (act *Actions) Load() error {
Comment is missing

2020-11-13 13:33 UTC, kalmant commented on uda/adjust/caloader.go
> +func NewCorporateActions(symbol string) *Actions {
Comment

2020-11-13 13:33 UTC, kalmant commented on uda/adjust/caloader.go
> +package adjust
A lot of things are exported. Is it necessary every single time?

2020-11-13 13:33 UTC, kalmant commented on uda/adjust/caloader.go
> +var cache = map[CacheKey]RateChangeCache{}
You don't like `make` :)

2020-11-13 13:33 UTC, kalmant commented on uda/adjust/caloader.go
> +		if err.Error() == "No files returned from query parse" {
String matching on the error seems a bit dangerous

2020-11-13 13:33 UTC, kalmant commented on uda/adjust/caloader.go
> +		return err
Fatal calls `os.Exit` multiple times in this file

2020-11-13 13:33 UTC, kalmant commented on uda/adjust/caloader.go
> +		// log.Info("ID: %d, date: %+v, status: %d, rate: %+v\n", act.Rows.TextNumbers[i], act.Rows.entrydates[i], act.Rows.Statuses[i], ca.Rows.Rates[i])
Forgotten comment

2020-11-13 13:33 UTC, kalmant commented on uda/adjust/caloader.go
> +			changes = append(changes, RateChange{Epoch: act.Rows.ExpirationDates[index], Rate: act.Rows.Rates[index], Textnumber: act.Rows.TextNumbers[index], Type: act.Rows.NotificationTypes[index]})
Suuuuuuuuuuper long line

2020-11-13 13:33 UTC, kalmant commented on uda/adjust/caloader.go
> +func (act *Actions) RateChangeEvents(includeSplits, includeDividends bool) []RateChange {
No comment and super difficult to understand. Is there a way this could be split up into more functions in a sensible way?

2020-11-13 13:33 UTC, kalmant commented on uda/adjust/caloader.go
> +			changes = append(changes, RateChange{Epoch: act.Rows.ExpirationDates[index], Rate: act.Rows.Rates[index], Textnumber: act.Rows.TextNumbers[index], Type: act.Rows.NotificationTypes[index]})
long

2020-11-13 13:33 UTC, kalmant commented on uda/adjust/recalc.go
> +	rn := new(Adjust)
Why the manual `new` here?

2020-11-13 13:33 UTC, kalmant commented on uda/adjust/recalc.go
> +	// reset some inner state here
Is this intentionally empty? If so, please clarify the comment.

2020-11-13 13:33 UTC, kalmant commented on uda/adjust/recalc.go
> +type Adjust struct {
There are a lot of seemingly unused methods here but eventually I realized it's because it's fulfilling an interface. Perhaps you could add this as a comment and [verify interface compliance](https://github.com/uber-go/guide/blob/master/style.md#verify-interface-compliance).

2020-11-15 18:20 UTC, kulcsarb commented on contrib/ice/ftp/downloader.go
> +	filenames := make([]string, 0)
I considered using empty declarations, but they are unnecessary in simple cases, and also lead to more clutter. Capacity considerations are a valid point, but
- these functions are running once per day so performance is not an issue
- the maximum capacity is unknown in some cases (like in sirs/collect.go)
- calculating the exact capacity would require more lines in the code and would add nothing to the performance of these functions.

2020-11-15 18:45 UTC, kulcsarb commented on contrib/ice/sirs/collect.go
> +func CollectSirsFilesFor(sirsFile string) ([]string, error) {
Unfortunately, you are right about what the function does :D It was indeed confusing but that mostly orignatesfrom the problem itself (I have a reorg file, then I had to find the matching sirs file, then I had to collect all previous few sirs file for the current sirs file.. erh). Nevertheless, thanks for bringing up this issue, I've cleaned it up a little bit.

2020-11-15 19:03 UTC, kulcsarb commented on contrib/ice/sirs/collect.go
> +	return filenames, nil
I tend to prefer simple and straightforward solutions, especially when the problem is at hand quite trivial. In this case the first item of the slice is just a filename, technically no different than the following files. Also, the "snapshot" file doesn't require any special processing, it behaves exactly like the following ones. Imho, every abstraction should have a usage - if there's no problem to solve with a custom type then why declaring and maintaining it ?

2, Not necessarily... `BuildSecurityMasterMap` is a very narrow and specific function to extract only cusip -> symbol mappings, while `CollectSirsFilesFor` is general and can be reused later

2020-11-15 19:18 UTC, kulcsarb commented on contrib/ice/enum/enum.go
> +const (
I've tried that way, but ended up too many direct type conversion through the code, so reverted back to leave them as plain bytes...

2020-11-15 19:18 UTC, kulcsarb commented on contrib/ice/cmd/sirs/show.go
> +				if symbol != "" {
yupp...

2020-11-15 19:32 UTC, kulcsarb commented on contrib/ice/ftp/client.go
> +func NewClient(username string, password string, ftp_host string) (FtpClient, error) {
Agree, but this function mimics goftp.DialConfig's pattern, which creates a new instance of itself, AND connects instantly to the target server. If you check their site, there's no way to create a Client struct separately and then use it to connect later :/

2020-11-15 19:53 UTC, kulcsarb commented on contrib/ice/ftp/client_mock.go
> +func NewMockClient() MockFtpClient {
Yupp, extensive tests should be written for the whole package... I hope I'll have time for that...

2020-11-15 19:58 UTC, kulcsarb commented on contrib/ice/ftp/client_mock.go
> +	Sys_     interface{}
os.FileInfo declares Sys() to return an interface{} type:
```type FileInfo interface {
    Name() string       // base name of the file
    Size() int64        // length in bytes for regular files; system-dependent for others
    Mode() FileMode     // file mode bits
    ModTime() time.Time // modification time
    IsDir() bool        // abbreviation for Mode().IsDir()
    Sys() interface{}   // underlying data source (can return nil)
}

2020-11-15 20:05 UTC, kulcsarb commented on contrib/ice/ftp/downloader.go
> +func (f *Downloader) filterPrefix(files []os.FileInfo) FileInfoMap {
changed it to simply "filter". I see your point but I don't feel necessary to split this function into two, especially since both path would be really small and always used together.

2020-11-15 20:07 UTC, kulcsarb commented on contrib/ice/ftp/downloader.go
> +			if _, exists := localfiles[remoteFileName+f.processedFlag]; !exists {
In case it is the result of a an aborted download from a previous run..

2020-11-15 20:09 UTC, kulcsarb commented on contrib/ice/ftp/downloader.go
> +			if remoteFile.Size() != localFile.Size() {
Since it's only for detecting aborted downloads I don't think it's necessary to go further. To my knowledge ICE won't modify an already published file.

2020-11-15 20:14 UTC, kulcsarb commented on contrib/ice/ftp/downloader.go
> +			if _, exists := localfiles[remoteFileName+f.processedFlag]; !exists {
preferred to stay in sync with the structure above, and I found it's less readable using `else if` on the same line

2020-11-15 20:19 UTC, kulcsarb commented on contrib/ice/ftp/downloader.go
> +		return []string{}
since Sync() only returns a string slice without an explicit error, returning a nil could cause exceptions in the caller function. It could be improved by returning a separate error variable, but I think it's an antipattern to return nil when an initialized slice/object/whatever is expected.

2020-11-15 20:25 UTC, kulcsarb commented on contrib/ice/lib/date/date.go
> +package date
It's a dependency needed by a the security master parsing code. I copied it from an another project and intentionally left it as is

2020-11-15 20:27 UTC, kulcsarb commented on uda/adjust/recalc.go
> +	rn := new(Adjust)
Following patterns of other uda/* functions here...

2020-11-15 20:28 UTC, kulcsarb commented on uda/adjust/recalc.go
> +	// reset some inner state here
needed by `AggInterface`

2020-11-18 09:46 UTC, tibkiss commented
Can we please include integration tests for this change?

2020-11-23 07:10 UTC, tibkiss commented
thanks for the unit tests, now back to my original ask:
Can we please include integration tests for this change? :)

2020-11-23 14:56 UTC, kulcsarb commented on contrib/ice/reorg/import.go
> +	localfiles, err := ioutil.ReadDir(path)
yeah, but go uses this if err != nil convention everywhere :/ Personally I prefer coding for the positive case as it makes the code more readable, but... sticking to golang conventions here...

2020-11-23 15:10 UTC, kulcsarb commented on contrib/ice/reorg/notification.go
> +func (i Notification) ParseDueRedemptionDate(lines []string) string {
yeah, the documentation states:    ```Only exported methods are accessible ``` Double checked to make sure, but using non-exported function names causes the whole parser to fail

2020-11-23 15:37 UTC, kulcsarb commented on frontend/query.go
> +		aggfunc.SetTimeBucketKey(tbk)
the Adjust function needs the TBK to find & load corporate actions data for the given symbol

2020-11-23 15:40 UTC, kulcsarb commented on uda/adjust/caloader.go
> +var cache = map[CacheKey]RateChangeCache{}
nope :D using literals makes it easier to read the code... at least for me :D

2020-11-23 15:41 UTC, kulcsarb commented on uda/adjust/caloader.go
> +		if err.Error() == "No files returned from query parse" {
yeah, but there's no other way to check this case :/

2020-11-25 12:41 UTC, tibkiss approved these changes
thanks, this is good to go!

2020-11-25 16:01 UTC, merged