ENH: Add unadjusted flag to polygon backfilling
alpacahq/marketstore pull request #391
Opened 2020-11-11 13:30 UTC by tibkiss

2020-11-12 15:26 UTC, kalmant reviewed
The code looks good but there's a conflict and some tests are failing. I'd approve it if those things were ✅

2020-11-12 15:30 UTC, kalmant requested changes
`contrib/polygon/polygon.go`

2020-11-12 15:30 UTC, kalmant commented on contrib/polygon/backfill/backfill.go
> +func Bars(symbol string, from, to time.Time, batchSize int, unadjusted bool, writerWP *worker.WorkerPool) (err error) {
`contrib/polygon/polygon.go` also uses this function but that file was not updated alongside these changes.

2020-11-13 07:01 UTC, tibkiss commented on contrib/polygon/backfill/backfill.go
> +func Bars(symbol string, from, to time.Time, batchSize int, unadjusted bool, writerWP *worker.WorkerPool) (err error) {
very good catch, thanks!

2020-11-18 09:51 UTC, tibkiss commented
closing in favor of https://github.com/alpacahq/marketstore/pull/384

2020-11-18 09:51 UTC, closed without merging